#FOR DATABASE CONNECTION
spring:
  application:
    name: backend_expantra
  datasource:
    url: jdbc:postgresql://localhost:5432/Expantra
    username: postgres
    password: "]})SqL({[100"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql : true
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.postgreSQLDialect

#FOR EMAIL SENDER SERVICE
  mail:
    host: smtp.gmail.com
    port: 587
    username: <Your_From_Email>
    password: <Your_App_Password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        connection timeout: 5000
        timeout: 3000
        write timeout: 5000

#FOR JWT
application:
  security:
    jwt:
      secretKey: tGYA-QQzbSjjUj2uYR31KPecdTRBliGOpGKUVNJY8WY
      jwtExpiration: 83600000